### ISSUE TITLE
KeyError for arguments for '--login' and '--password'

### ISSUE THREAD

**Issue by bitstein** [csaftoiu/yahoo-groups-backup#2]
```scraper = YahooBackupScraper(arguments['<group_name>'], arguments['--login'], arguments['--password'])```

Login and password are never set in the command line parser, so it raises a `KeyError` exception. My quick local fix was to just add each to the `arguments` dictionary as `None`.

**Comment by bitstein** [comment]
I see now. You are pulling from `settings.yaml`. Closing.

**Comment by csaftoiu** [comment]
Thanks for the feedback! Actually my intention was that it would work without a settings and without passing in a login & password for public groups. Reopening and putting in a fix now.
