### ISSUE TITLE
Syntax error when attempting to run

### ISSUE THREAD

**Issue by megaminxwin** [csaftoiu/yahoo-groups-backup#36]
When I run the script, I keep getting this message:

      File "./yahoo-groups-backup.py", line 56
        result = {**default_args, **cfg_args}
                   ^
    SyntaxError: invalid syntax

I'm pretty sure I installed everything just fine, so I'm really not sure what's going on here...

**Comment by csaftoiu** [comment]
Ah this is a new feature in Python 3.5, I'll add the requirement to the project page.
